/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voidSpirit.productCycle.view;

import com.voidSpirit.productCycle.controller.ProdukController;
import com.voidSpirit.productCycle.model.pojo.JenisProduk;
import com.voidSpirit.productCycle.model.pojo.Produk;
import com.voidSpirit.productCycle.utilites.ProdukUtilities;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Zikri
 */
public class KelolaProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form KelolaProdukFrame
     */
    private DefaultTableModel model;
    ProdukController con = new ProdukController();

    public KelolaProdukFrame() throws SQLException {
        initComponents();
        ukuranKolom();
        isiKolom();
        this.setLocationRelativeTo(null);
        populateDataToTable();
    }

    public void isiKolom() throws SQLException {
        List<Produk> prd = con.lihatJenis();

        cmbJenis.removeAllItems();
        cmbJenis.addItem("-- Pilih Jenis --");
        for (Produk pr : prd) {
            cmbJenis.addItem(pr.getNamaJenis());
        }
    }

    private void isiField() {
        tfId.setText("");
        tfNama.setText("");
        cmbJenis.setSelectedIndex(0);
        tfStok.setText("");
        tfHarga.setText("");
    }

    public void populateDataToTable() throws SQLException {
        model = (DefaultTableModel) tblProduk.getModel();
        List<Produk> prd = con.lihatProduk();
        int i = 0;

        for (Produk pr : prd) {
            Object[] row = new Object[5];
            row[0] = ++i;
            row[1] = pr.getNamaProduk();
            row[2] = pr.getNamaJenis();
            row[3] = pr.getHargaProduk();
            row[4] = pr.getStokProduk();
            model.addRow(row);
        }
    }

    public void ukuranKolom() {
        TableColumn column;
        tblProduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tblProduk.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tblProduk.getColumnModel().getColumn(1);
        column.setPreferredWidth(275);
        column = tblProduk.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = tblProduk.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tblProduk.getColumnModel().getColumn(4);
        column.setPreferredWidth(100);
    }

    public void refreshTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
        model.setRowCount(0);
        populateDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        tfHarga = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        lblIdProduk = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btnTambahJenis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfMenu = new javax.swing.JTextField();

        jLabel1.setText("Kelola Barang");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clear Symbol-48.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nama", "Jenis", "Harga Satuan", "Stok"
            }
        ));
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-64.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-material-filled-64.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-64.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("KELOLA PRODUK");

        lblNama.setText("Nama Produk  ");

        lblJenis.setText("Jenis Produk   ");

        lblHarga.setText("Harga Satuan ");

        lblStok.setText("Stok Produk   ");

        tfHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfHargaKeyTyped(evt);
            }
        });

        tfStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfStokKeyTyped(evt);
            }
        });

        lblIdProduk.setText("Id Produk");

        tfId.setEnabled(false);

        btnTambahJenis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-menu-64.png"))); // NOI18N
        btnTambahJenis.setText("Tambah Menu");
        btnTambahJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahJenisActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis baru :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblIdProduk)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblNama, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblJenis, javax.swing.GroupLayout.Alignment.TRAILING))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblStok)
                                                .addComponent(lblHarga)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfStok)
                                            .addComponent(tfNama)
                                            .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTambahJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(408, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnKembali))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdProduk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbJenis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStok)
                            .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int id;
        tfId.getText();
        String nama = tfNama.getText();
        String jenis = (String) cmbJenis.getSelectedItem();
        int stok;
        int harga;
        if (!tfId.getText().equals("")) {
            id = Integer.valueOf(tfId.getText());
        } else {
            id = 0;
        }
        if (!tfStok.getText().equals("")) {
            stok = Integer.parseInt(tfStok.getText());
        } else {
            stok = 0;
        }
        if (!tfHarga.getText().equals("")) {
            harga = Integer.parseInt(tfHarga.getText());
        } else {
            harga = 0;
        }
        int status = 0;
        if (ProdukUtilities.checkDataId(id)) {
            if (ProdukUtilities.checkData(new Produk(nama, jenis, stok, harga))) {
                try {
                    status = con.ubahProduk(new Produk(id, nama, jenis, harga, stok));
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (status == 1) {
                    try {
                        refreshTable();
                    } catch (SQLException ex) {
                        Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "Produk " + nama + " berhasil di Ubah");
                } else {
                    JOptionPane.showMessageDialog(this, "Produk gagal di Ubah");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih yang ingin diubah");
        }
        isiField();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int id;
        int status = 0;
        if (!tfId.getText().equals("")) {
            id = Integer.valueOf(tfId.getText());
        } else {
            id = 0;
        }
        if (ProdukUtilities.checkDataId(id)) {
            try {
                status = con.hapusProduk(id);
            } catch (SQLException ex) {
                Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (status == 1) {
                try {
                    refreshTable();
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Produk dengan id " + id + " berhasil di Hapus");
            } else {
                JOptionPane.showMessageDialog(this, "Produk gagal diHapus");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan pilih yang poduk yang ingin dihapus");
        }

        isiField();

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama = tfNama.getText();
        String jenis = (String) cmbJenis.getSelectedItem();
        int stok;
        int harga;
        if (!tfStok.getText().equals("")) {
            stok = Integer.parseInt(tfStok.getText());
        } else {
            stok = 0;
        }
        if (!tfHarga.getText().equals("")) {
            harga = Integer.parseInt(tfHarga.getText());
        } else {
            harga = 0;
        }
        int status = 0;

        if (ProdukUtilities.checkData(new Produk(nama, jenis, stok, harga))) {
            try {
                status = con.tambahProduk(new Produk(nama, jenis, harga, stok));
            } catch (SQLException ex) {
                Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (status == 1) {
                try {
                    refreshTable();
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Produk " + nama + " berhasil ditambahkan");
            } else {
                JOptionPane.showMessageDialog(this, "Produk gagal ditambahkan");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Inputan tidak boleh kosong");
        }

        isiField();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahJenisActionPerformed
        // TODO add your handling code here:
        String jenis = tfMenu.getText();

        int status = 0;

        if (ProdukUtilities.checkData(jenis)) {
            try {

                DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
                status = con.tambahJenis(new JenisProduk(jenis));

                isiKolom();

            } catch (SQLException ex) {
            }
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Jenis " + jenis + " berhasil ditambahkan");
            } else {
                JOptionPane.showMessageDialog(this, "Jenis gagal ditambahkan");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inputan tidak boleh kosong");
        }

    }//GEN-LAST:event_btnTambahJenisActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
        int selectedIndex = tblProduk.getSelectedRow();

        String nama = model.getValueAt(selectedIndex, 1).toString();
        String jenis = model.getValueAt(selectedIndex, 2).toString();
        int harga = (int) model.getValueAt(selectedIndex, 3);
        int stok = (int) model.getValueAt(selectedIndex, 4);

        try {
            int id = con.cariId(new Produk(nama, jenis, harga, stok));
            tfId.setText(Integer.toString(id));
            tfNama.setText(nama);
            cmbJenis.setSelectedItem(jenis);
            tfHarga.setText(model.getValueAt(selectedIndex, 3).toString());
            tfStok.setText(model.getValueAt(selectedIndex, 4).toString());
        } catch (SQLException ex) {
            Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblProdukMouseClicked

    private void tfHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHargaKeyTyped
        // TODO add your handling code here:
        ProdukUtilities.checkNumber(evt);
    }//GEN-LAST:event_tfHargaKeyTyped

    private void tfStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStokKeyTyped
        // TODO add your handling code here:
        ProdukUtilities.checkNumber(evt);
    }//GEN-LAST:event_tfStokKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KelolaProdukFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahJenis;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIdProduk;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStok;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMenu;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables
}
