/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voidSpirit.productCycle.view;

import com.voidSpirit.productCycle.controller.ProdukController;
import com.voidSpirit.productCycle.model.pojo.Produk;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Zikri
 */
public class KelolaProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form KelolaProdukFrame
     */
    
    private DefaultTableModel model;
    ProdukController con = new ProdukController();
    
    public KelolaProdukFrame() throws SQLException {
        initComponents();
        populateDataToTable();
        ukuranKolom();
        this.setLocationRelativeTo(null);
    }
    
    public void populateDataToTable() throws SQLException {
        model = (DefaultTableModel) tabelProduk.getModel();
          List<Produk> prd = con.lihatProduk();
          int i = 0;

        for (Produk pr : prd) {
            Object[] row = new Object[5];
            row[0] = ++i;
            row[1] = pr.getNamaProduk();
            row[2] = pr.getIdJenisProduk();
            row[3] = pr.getHargaProduk();
            row[4] = pr.getStokProduk();
            model.addRow(row);
        }
    }
    
    public void ukuranKolom(){ 
        TableColumn column;
        tabelProduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tabelProduk.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tabelProduk.getColumnModel().getColumn(1); 
        column.setPreferredWidth(200); 
        column = tabelProduk.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200); 
        column = tabelProduk.getColumnModel().getColumn(3); 
        column.setPreferredWidth(200); 
        column = tabelProduk.getColumnModel().getColumn(4); 
        column.setPreferredWidth(100); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        btnKembali1 = new javax.swing.JButton();
        btnKembali2 = new javax.swing.JButton();
        btnKembali3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Kelola Barang");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clear Symbol-48.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nama", "Jenis", "Harga Satuan", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        btnKembali1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-64.png"))); // NOI18N
        btnKembali1.setText("Tambah");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });

        btnKembali2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-material-filled-64.png"))); // NOI18N
        btnKembali2.setText("Ubah");
        btnKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali2ActionPerformed(evt);
            }
        });

        btnKembali3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-64.png"))); // NOI18N
        btnKembali3.setText("Hapus");
        btnKembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("KELOLA PRODUK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKembali1)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembali2)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembali3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKembali)))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali1)
                    .addComponent(btnKembali2)
                    .addComponent(btnKembali3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        new TambahProdukFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembali1ActionPerformed

    private void btnKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembali2ActionPerformed

    private void btnKembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembali3ActionPerformed

    
//    public void lihatProduk() {
//        model = (DefaultTableModel) tabelProduk.getModel();
//        ProdukController con = new ProdukController();
//        Produk[] pr;
//        
//        for(int i = 0; i < pr.length; i++) {
//            String[] row = new String[5];
//            row[0] = ""+(i+1);
//            row[1] = pr[i].getNamaProduk();
//            row[2] = pr[i].getIdJenisProduk();
//            row[3] = pr[i].getHargaProduk();
//            row[4] = pr[i].getStokProduk();
//            model.addRow(row);
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KelolaProdukFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KelolaProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnKembali2;
    private javax.swing.JButton btnKembali3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    // End of variables declaration//GEN-END:variables
}
