/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.voidSpirit.productCycle.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Zikri
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHalUtama = new javax.swing.JLabel();
        btnPindahTambah = new javax.swing.JButton();
        btnPindahKelola = new javax.swing.JButton();
        btnPindahPenjualan = new javax.swing.JButton();
        lblTambahBarangBaru = new javax.swing.JLabel();
        lblKelolaBarang = new javax.swing.JLabel();
        lblPenjulanProduk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHalUtama.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHalUtama.setText("Halaman Utama");

        btnPindahTambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zikri\\Documents\\NetBeansProjects\\VoidSpirit\\assets\\1.png")); // NOI18N
        btnPindahTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindahTambahActionPerformed(evt);
            }
        });

        btnPindahKelola.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zikri\\Documents\\NetBeansProjects\\VoidSpirit\\assets\\2.png")); // NOI18N
        btnPindahKelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindahKelolaActionPerformed(evt);
            }
        });

        btnPindahPenjualan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zikri\\Documents\\NetBeansProjects\\VoidSpirit\\assets\\3.png")); // NOI18N

        lblTambahBarangBaru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTambahBarangBaru.setText("Penjualan Produk");

        lblKelolaBarang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblKelolaBarang.setText("Kelola Barang");

        lblPenjulanProduk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPenjulanProduk.setText("Pelaporan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lblHalUtama))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblKelolaBarang)
                                .addGap(59, 59, 59)
                                .addComponent(lblTambahBarangBaru)
                                .addGap(58, 58, 58)
                                .addComponent(lblPenjulanProduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPindahKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPindahTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPindahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHalUtama)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPindahKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPindahPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPindahTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKelolaBarang)
                        .addComponent(lblTambahBarangBaru))
                    .addComponent(lblPenjulanProduk))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPindahTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindahTambahActionPerformed
        new TambahProdukFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPindahTambahActionPerformed

    private void btnPindahKelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindahKelolaActionPerformed
        try {
            new KelolaProdukFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnPindahKelolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPindahKelola;
    private javax.swing.JButton btnPindahPenjualan;
    private javax.swing.JButton btnPindahTambah;
    private javax.swing.JLabel lblHalUtama;
    private javax.swing.JLabel lblKelolaBarang;
    private javax.swing.JLabel lblPenjulanProduk;
    private javax.swing.JLabel lblTambahBarangBaru;
    // End of variables declaration//GEN-END:variables
}
